### ISSUE TITLE
KeyError: 'transport_id'

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/frida-push#8]
**Host System:** Ubuntu 16.04
I am running my Android x86 VM using Genymotion

**Adb devices:**

```
testing$ adb devices -l
List of devices attached
192.168.65.101:5555    device product:vbox86p model:Custom_Phone___7_1_0___API_25___768x1280 device:vbox86p
```

**Error:**
```
testing$ frida-push 
[2018-06-30 21:34:44,726] [frida-push: INFO]: Devices: 192.168.65.101:5555
[2018-06-30 21:34:44,727] [frida-push: INFO]: Current installed Frida version: 11.0.12
Traceback (most recent call last):
  File "/home/c0d3r/temp/testing/testing/bin/frida-push", line 11, in <module>
    sys.exit(main())
  File "/home/c0d3r/temp/testing/testing/local/lib/python2.7/site-packages/frida_push/command.py", line 211, in main
    transport_id = devices[ops.device_name]['transport_id']
KeyError: 'transport_id'
```

**Comment by eugenekolo** [comment]
@Chan9390 update your `adb`. 

Later versions of `adb` added the 'transport_id' key.
